// Mini printf / sprintf auto-included when the user calls them without
// providing their own definitions.
//
// Supports %d (signed int16), %s (char*), %c (int as char), %%. Other format
// specifiers print literally ("%x" emits "%x"). The format string may be any
// expression — it is not restricted to string literals.
//
// Variadic calls in c8080-js use a dedicated `__va_args[]` buffer rather than
// the CPU stack: the caller stores extra arguments into successive word slots
// before the CALL, and the callee walks them as it encounters format specs.
//
// printf and sprintf share an output routing layer: `__printf_out_ptr` is
// NULL → bytes go to putchar; non-NULL → bytes are written to the buffer
// and the pointer advances. sprintf sets it up, calls the shared core, then
// NUL-terminates.

export const PRINTF_SOURCE = `
// Auto-generated by c8080-js: mini printf/sprintf runtime.
int __va_args[8];
char *__printf_out_ptr;

int __printf_putchar(int c) {
    if (__printf_out_ptr == (char*)0) { putchar(c); return 0; }
    *__printf_out_ptr = c;
    __printf_out_ptr = __printf_out_ptr + 1;
    return 0;
}

int __printf_putint(int val) {
    char buf[6];
    int j;
    if (val < 0) { __printf_putchar('-'); val = -val; }
    if (val == 0) { __printf_putchar('0'); return 0; }
    j = 0;
    while (val != 0) {
        buf[j] = '0' + (val % 10);
        j = j + 1;
        val = val / 10;
    }
    while (j > 0) {
        j = j - 1;
        __printf_putchar(buf[j]);
    }
    return 0;
}

int __printf_core(char *fmt) {
    int i;
    int c;
    char *s;
    i = 0;
    while (*fmt != 0) {
        c = *fmt;
        fmt = fmt + 1;
        if (c != '%') {
            __printf_putchar(c);
            continue;
        }
        c = *fmt;
        if (c == 0) break;
        fmt = fmt + 1;
        if (c == 'd') { __printf_putint(__va_args[i]); i = i + 1; }
        else if (c == 's') {
            s = (char*)__va_args[i];
            i = i + 1;
            while (*s != 0) { __printf_putchar(*s); s = s + 1; }
        }
        else if (c == 'c') { __printf_putchar(__va_args[i]); i = i + 1; }
        else if (c == '%') { __printf_putchar('%'); }
        else { __printf_putchar('%'); __printf_putchar(c); }
    }
    return 0;
}

int printf(char *fmt, ...) {
    __printf_out_ptr = (char*)0;
    __printf_core(fmt);
    return 0;
}

int sprintf(char *buf, char *fmt, ...) {
    char *start;
    start = buf;
    __printf_out_ptr = buf;
    __printf_core(fmt);
    *__printf_out_ptr = 0;
    return __printf_out_ptr - start;
}
`;

export const PRINTF_FUNCTION_NAMES: readonly string[] = [
  "printf", "sprintf", "__printf_core", "__printf_putint", "__printf_putchar",
];
