// Mini printf auto-included when user calls printf() without providing their own.
//
// Supports %d (signed int16), %s (char*), %c (int as char), %%. Other format
// specifiers print literally ("%x" emits "%x"). The format string may be any
// expression — it is not restricted to string literals.
//
// Variadic calls in c8080-js use a dedicated `__va_args[]` buffer rather than
// the CPU stack: the caller stores extra arguments into successive word slots
// before the CALL, and printf walks them as it encounters format specifiers.

export const PRINTF_SOURCE = `
// Auto-generated by c8080-js: mini printf runtime.
int __va_args[8];

int __printf_putint(int val) {
    char buf[6];
    int j;
    if (val < 0) { putchar('-'); val = -val; }
    if (val == 0) { putchar('0'); return 0; }
    j = 0;
    while (val != 0) {
        buf[j] = '0' + (val % 10);
        j = j + 1;
        val = val / 10;
    }
    while (j > 0) {
        j = j - 1;
        putchar(buf[j]);
    }
    return 0;
}

int printf(char *fmt, ...) {
    int i;
    int c;
    char *s;
    i = 0;
    while (*fmt != 0) {
        c = *fmt;
        fmt = fmt + 1;
        if (c != '%') {
            putchar(c);
            continue;
        }
        c = *fmt;
        if (c == 0) break;
        fmt = fmt + 1;
        if (c == 'd') { __printf_putint(__va_args[i]); i = i + 1; }
        else if (c == 's') {
            s = (char*)__va_args[i];
            i = i + 1;
            while (*s != 0) { putchar(*s); s = s + 1; }
        }
        else if (c == 'c') { putchar(__va_args[i]); i = i + 1; }
        else if (c == '%') { putchar('%'); }
        else { putchar('%'); putchar(c); }
    }
    return 0;
}
`;

export const PRINTF_FUNCTION_NAMES: readonly string[] = ["printf", "__printf_putint"];
